<?php
//$path="D:/wamp/www/erhan-proj/upload/";
//$dispath="http://localhost/erhan-proj/upload/";
$path="/www/hardikthakkar.net23.net/upload/";
$dispath="http://hardikthakkar.net23.net/upload/";
//$path="C:/apache2triad/htdocs/wedding/upload/";
//$path1="C:/apache2triad/htdocs/wedding/upload/thumb/";
//$dispath="http://localhost/wedding/upload/";
//$dispath1="http://localhost/wedding/upload/thumb/";
//$pathpdf="http://localhost/wedding/upload/pdf/";
//$path="/home/holycare/public_html/upload/";
//$path1="/home/holycare/public_html/upload/thumb/";
//$dispath="http://www.holycare.org/upload/";
//$dispath1="http://www.holycare.org/upload/thumb/";
?>